name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --features clap --features dhall --features env --features ini --features json --features toml --features yaml --verbose
      - name: Install cargo hack
        run: cargo install cargo-hack
      - name: Run cargo hack
        run: cargo hack check --each-feature --no-dev-deps
